name: transport_manager
description: Transport Fleet Management App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: 2.2.8
  path: 1.8.3
  pdf: 3.10.4
  printing: 5.11.0
  share_plus: 6.3.2
  url_launcher: 6.1.12
  path_provider: 2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
