name: transport_manager
description: Transport Fleet Management Ultra Pro Max ERP
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  pdf: ^3.10.4
  printing: ^5.11.1
  cupertino_icons: ^1.0.6
  url_launcher: ^6.3.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
