name: transport_manager
description: Transport Fleet Management App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  pdf: ^3.10.4
  printing: ^5.11.1
  cupertino_icons: ^1.0.6
  
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path: ^1.9.1
  pdf: ^3.10.4
  printing: ^5.11.0
  share_plus: ^10.0.0
  url_launcher: ^6.3.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
